# Display help
help:
    just -l

# Install the `seeky-tui` binary
install:
    cargo install --path tui

# Run the TUI app
tui *args:
    cargo run --bin seeky -- tui {{args}}

# Run the Proto app
proto *args:
    cargo run --bin seeky -- proto {{args}}
