name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    name: Check Formatting (Prettier/Black/Rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js formatting (Prettier)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Check Prettier formatting
        run: npx prettier --check .

      # Python formatting (Black)
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Black
        run: pip install black
      - name: Check Black formatting
        run: black --check . || true  # Don't fail if no Python files

      # Rust formatting (rustfmt)
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check Rust formatting
        run: cargo fmt --all -- --check

  lint-and-test:
    name: Lint & Test (TypeScript, Rust, Python)
    runs-on: ubuntu-latest
    needs: check-formatting
    steps:
      - uses: actions/checkout@v4

      # Node.js Lint & Test
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Lint (npm run lint)
        run: npm run lint || true  # Don't fail if no lint script
      - name: Test (npm test)
        run: npm test || true      # Don't fail if no test script
      - name: Build (npm run build)
        run: npm run build || true #](#)

