name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    name: Check Formatting (Prettier/Black/Rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js formatting (Prettier)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: . # Adjust if your package.json is elsewhere
      - run: npx prettier --check .
        working-directory: .

      # Python formatting (Black)
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install black
      - name: Run Black
        run: black --check .
        continue-on-error: true # Optional: don't fail if no Python files

      # Rust formatting (rustfmt)
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo fmt --all -- --check

  lint-and-test:
    name: Lint & Test (TS, Rust, Python)
    runs-on: ubuntu-latest
    needs: check-formatting
    steps:
      - uses: actions/checkout@v4

      # Node.js Lint & Test
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: .
      - run: npm run lint
        working-directory: .
      - run: npm test
        working-directory: .
      - run: npm run build
        working-directory: .

      # Python Lint & Test
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Python requirements if present
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - run: pip install pytest
      - name: Run Pytest
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest
          fi

      # Rust Lint & Test
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo clippy --all -- -D warnings
      - run: cargo test --all
